service: express-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    NODE_ENV: production
    MONGO_URI: ${env:URI} # Đảm bảo bạn có biến môi trường trong .env

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - README.md

custom:
  dotenv:
    basePath: ./ # Đảm bảo dotenv đọc từ file .env
